### ISSUE TITLE
From "maltego.Company" To "Company"

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-FullContact#3]
From "_Company_" `maltego.Company` To [`Company Lookup`](https://www.fullcontact.com/developer/docs/company/#lookup-by-company-name)

`maltego.Company` is part of  `CaseFile Entities` on the the Transform Hub

**Comment by tendai-zw** [comment]
Hi there is a spelling error on the wiki,  you have maltego.company. It should be should be maltego.Company

**Comment by cmlh** [comment]
@tendai-zw Many thanks, I have committed a fix as https://github.com/cmlh/Maltego-FullContact/wiki/Home/dbe5b7bb2af3bf1a0e3902677c12bc484367fbae

**Comment by cmlh** [comment]
Supported.
